os:
  - linux

language: erlang

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=5.2

sudo: false

dist: trusty

git:
  depth: 5

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks make
  - luarocks install busted

script:
  - ./bin/build.sh
  - busted spec
