os:
  - linux

language: erlang

env:
  - LUA=""
  - LUA="luajit"

sudo: false

dist: trusty

addons:
  apt:
    packages:
      - lua5.2

git:
  depth: 5

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted

script: ./bin/build.sh
